---
title: "Simple document"
output: html_document
---

```{r, echo = FALSE, mesaage = FALSE}
library(tidyverse)
```

I'm an R Markdown document! 

# Section 1

Here's a **code chunk** that samples from 
a _normal distribution_:

```{r}
samp = rnorm(100)
length(samp)
```

# Section 2

I can take the mean of the sample, too!
The mean is `r round(mean(samp), 2)`.

# Section 3

## Plot from last time

This is going to make a plot! First I generate a dataframe, then use `ggplot` to make a scatterplot.

```{r chunk_scatterplot}
# option + command + i

plot_df =
  tibble(
    x = rnorm(n = 1000), # rnorm() for a normal distribution
    y = 1 + 2 * x + rnorm(n = 1000)
  )

ggplot(plot_df, aes(x = x, y = y)) + geom_point()
```

```{r chunk_histogram}
ggplot(plot_df, aes(x = x)) + geom_histogram()
```

## Plot for Learning Assessment
```{r learning_assessment_1}
la_df =
  tibble(
    norm = rnorm(n = 500, mean = 1),
    logical = norm > 0,
    abs_norm = abs(norm)
  )

ggplot(la_df, aes(x = abs_norm)) + geom_histogram()
```

Here's a list:

*   Item 1

*   Item 2

    * Item 2a

    * Item 2b